service: tasks-api

useDotenv: true

provider:
  name: aws
  runtime: python3.13
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'development'}
  logRetentionInDays: 30
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}

functions:
  API:
    handler: main.handle
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60

custom:
  pythonRequirements:
    useUv: true
    fileName: requirements.txt
    noDeploy:
      - boto3
      - botocore

plugins:
  - serverless-python-requirements
