name: API Test and deploy
on:
  push:
    paths:
      - "services/tasks_api/**"
      - ".github/workflows/api.yml"

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: services/tasks_api
    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run ruff
        run: uv run ruff check . --output-format=github
      - name: Check formatting
        run: uv run ruff format --check .

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: services/tasks_api
    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Test code
        run: uv run pytest tests.py --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
